### ISSUE TITLE
能否增加一个定投功能

### ISSUE THREAD

**Issue by Echoleung** [Hurdery/jfc#2]
好几个基金每天定投10块，希望可以有一个定投功能可以设置持有每天自己增加10块

**Comment by ghost** [comment]
我觉得没法帮你操作吧，你是场外交易，都是要通过各个第三方平台操作的。

**Comment by Hurdery** [comment]
> 好几个基金每天定投10块，希望可以有一个定投功能可以设置持有每天自己增加10块

代码实现上很简单，在你基金持仓里面，每天增加10块。但是需要考虑一个问题，这个功能是否有必要，其他基民需不需要，当然如果这个需求提的人多了，会考虑的
