### ISSUE TITLE
优化软件打包大小

### ISSUE THREAD

**Issue by liyiecho** [Hurdery/jfc#7]
软件只有500多KB，下载包却有47.7 MB
![QQ20201029-192055](https://user-images.githubusercontent.com/5213722/97562133-2493bb00-1a1c-11eb-8863-bd1a50f648a1.jpg)
![image](https://user-images.githubusercontent.com/5213722/97562208-3a08e500-1a1c-11eb-8c81-67816a159008.png)

**Comment by Hurdery** [comment]
封包的时候好像有个默认大小，不过取决于你实际使用大小，影响不大。



发自我的iPhone


------------------ 原始邮件 ------------------
寄件人： liyiecho <notifications@github.com&gt;
发送时间: 2020年10月29日 19:24
收件人： Hurdery/jfc <jfc@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主旨： 回覆：[Hurdery/jfc] 优化软件打包大小 (#7)





 
软件只有500多KB，下载包却有47.7 MB
