### ISSUE TITLE
Big Sur 无法安装， 点击dmg文件无反应

### ISSUE THREAD

**Issue by ChenRiliang** [Hurdery/jfc#8]
![image](https://user-images.githubusercontent.com/30994257/105436717-a94c4900-5c9a-11eb-89d9-3f61487c3073.png)

配置如图， 能否徐告知如何处理？

**Comment by Hurdery** [comment]
双击，然后看下桌面有无未命名磁盘，如无，可以加群和群友共同探讨

**Comment by ChenRiliang** [comment]
> 双击，然后看下桌面有无未命名磁盘，如无，可以加群和群友共同探讨

感谢， 看到了， 可以了。

**Comment by Hurdery** [comment]
认证阅读使用说明书
